blog/models.py
# blog/models.py
from datetime import datetime
from blog import db

class Entry(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200))
    body = db.Column(db.Text)
    pub_date = db.Column(db.DateTime, default=datetime.utcnow)
    is_published = db.Column(db.Boolean, default=False)

blog/forms.py
# blog/forms.py
from werkzeug.routing import ValidationError
from wtforms import StringField, PasswordField
from .config import Config
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])

    def validate_username(self, field):
        if field.data != Config.ADMIN_USERNAME:
            raise ValidationError("Invalid username")
        return field.data

    def validate_password(self, field):
        if field.data != Config.ADMIN_PASSWORD:
            raise ValidationError("Invalid password")
        return field.data


class EntryForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = TextAreaField('Body', validators=[DataRequired()])
    is_published = BooleanField('Published', default=True)

blog/__init__.py
#blog/_init_.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from blog.config import Config

db = SQLAlchemy()
migrate = Migrate()


def create_app():
    app = Flask(__name__)
    app.debug = True
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)

    from blog.routes import bp
    app.register_blueprint(bp)

    from blog.fake_data import generate_entries

    return app

blog/routes.py
# blog/routes.py
from blog.forms import EntryForm, LoginForm
from flask import render_template, request, session, Blueprint
import functools
from flask import redirect, url_for, flash
from blog.models import Entry, db


bp = Blueprint('blog', __name__)


def login_required(view_func):
   @functools.wraps(view_func)
   def check_permissions(*args, **kwargs):
       if session.get('logged_in'):
           return view_func(*args, **kwargs)
       return redirect(url_for('blog.login', next=request.path))
   return check_permissions


@bp.route('/')
def index():
    # Query published posts from the database
    all_posts = Entry.query.filter_by(is_published=True).order_by(Entry.pub_date.desc()).all()

    # Pass the list of posts to the template
    return render_template('homepage.html', all_posts=all_posts)


@bp.route('/drafts/', methods=['GET'])
@login_required
def list_drafts():
    drafts = Entry.query.filter_by(is_published=False).order_by(Entry.pub_date.desc())
    return render_template("drafts.html", drafts=drafts)


@bp.route("/new-form/", methods=["GET", "POST"])
@login_required
def create_entry():
    return entry_form(entry_id=None)


@bp.route("/edit-post/<int:entry_id>/", methods=["GET", "POST"])
@login_required
def edit_entry(entry_id):
    return entry_form(entry_id)


def entry_form(entry_id=None):
    entry = None
    if entry_id:
        entry = Entry.query.filter_by(id=entry_id).first_or_404()
    form = EntryForm(obj=entry)
    if form.validate_on_submit():
        if entry_id:
            entry.title = form.title.data
            entry.body = form.body.data
            entry.is_published = form.is_published.data
            db.session.commit()
        else:
            entry = Entry(
                title=form.title.data,
                body=form.body.data,
                is_published=form.is_published.data
            )
            db.session.add(entry)
            db.session.commit()
        return redirect(url_for('blog.index'))

    return render_template("entry_form.html", form=form)


@bp.route("/login/", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    errors = None
    next_url = request.args.get('next')
    if request.method == 'POST':
        if form.validate_on_submit():
            session['logged_in'] = True
            session.permanent = True  # Use cookie to store session.
            flash('You are now logged in.', 'success')
            return redirect(next_url or url_for('blog.index'))
        else:
            errors = form.errors
    return render_template("login_form.html", form=form, errors=errors)


@bp.route('/logout/', methods=['GET', 'POST'])
def logout():
    if request.method == 'POST':
        session.clear()
        flash('You are now logged out.', 'success')
    return redirect(url_for('blog.index'))


@bp.route('/delete_entry/<int:entry_id>', methods=['POST', 'DELETE'])
@login_required
def delete_entry(entry_id):
    entry = Entry.query.filter_by(id=entry_id).first_or_404()
    db.session.delete(entry)
    db.session.commit()
    flash('Post deleted successfully.', 'success')
    return redirect(url_for('blog.list_drafts'))

blog/templates/base.html
<!doctype html>
<html lang="en">

<head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 <meta name="description" content="">
 <title>Мій перший блог</title>

 <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">

 <!-- Bootstrap core CSS -->
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
   integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

 <style>
   body {
     padding-top: 5rem;
   }
 </style>
</head>

<body>
 <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
   <a class="navbar-brand" href="#">Мій блог</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
     aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>

   <div class="collapse navbar-collapse">
     <ul class="navbar-nav mr-auto">

         <div class="collapse navbar-collapse">
     <ul class="navbar-nav mr-auto">
     </ul>
     {% if session.logged_in %}
       <form class="form-inline my-2 my-lg-0" action="{{ url_for('blog.logout') }}" method="POST">
         <button class="btn btn-secondary my-2 my-sm-0" type="submit">Вийди</button>
       </form>
     {% else %}
       <a href="{{ url_for('blog.login') }}" class="btn btn-secondary my-2 my-lg-0">Zaloguj</a>
     {% endif %}
   </div>



     </ul>
     <form class="form-inline my-2 my-lg-0">
     <input class="form-control mr-sm-2" type="text" placeholder="Шукати" aria-label="Шукати ">
     <button class="btn btn-secondary my-2 my-sm-0" type="submit">Шукати </button>
     </form>
   </div>
 </nav>

 <main role="main" class="container">

   {% block content %}
   {% endblock %}

 </main><!-- /.container -->
 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
   integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
   crossorigin="anonymous"></script>
 <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
   integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
   crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
   integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
   crossorigin="anonymous"></script>

</body>

</html>

blog/templates/drafts.html
<!-- blog/templates/drafts.html -->
{% extends "base.html" %}

{% block content %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Title</th>
        <th scope="col">Content</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for post in drafts %}
        <tr>
          <td>{{ post.pub_date.strftime('%Y-%m-%d') }}</td>
          <td>
            <a href="{{ url_for('blog.edit_entry', entry_id=post.id) }}">
              {{ post.title }}
            </a>
          </td>
          <td>{{ post.body|truncate(100, true) }}</td>
          <td>
            <form action="{{ url_for('blog.delete_entry', entry_id=post.id) }}" method="POST">
              <input type="hidden" name="_method" value="DELETE">
              <button type="submit" class="btn btn-sm btn-danger">Delete</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

blog/templates/entry_form.html
<!-- blog/templates/entry_form.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>{% if form.obj %}Edit{% else %}New{% endif %} Entry</h2>
  <form method="POST" action="{% if form.obj %}{{ url_for('blog.edit_entry', entry_id=form.obj.id) }}{% else %}{{ url_for('blog.create_entry') }}{% endif %}" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.title.label }} {{ form.title(size=50) }}
      {% if form.title.errors %}
        <ul class="errors">
          {% for error in form.title.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.body.label }} {{ form.body(rows=10) }}
      {% if form.body.errors %}
        <ul class="errors">
          {% for error in form.body.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.is_published.label }} {{ form.is_published() }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

blog/templates/homepage.html
<!-- blog/templates/homepage.html -->
{% extends "base.html" %}

{% block content %}

{% for post in all_posts %}
    {% if post.is_published %}
        <div>
            <div>
                <h2 class="d-inline-block">{{ post.title }}</h2>
                <<a href="{{ url_for('blog.edit_entry', entry_id=post.id) }}">
                    <svg class="bi bi-pencil float-right" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M11.293 1.293a1 1 0 0 1 1.414 0l2 2a1 1 0 0 1 0 1.414l-9 9a1 1 0 0 1-.39.242l-3 1a1 1 0 0 1-1.266-1.265l1-3a1 1 0 0 1 .242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z"/>
                        <path fill-rule="evenodd" d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 0 0 .5.5H4v.5a.5.5 0 0 0 .5.5H5v.5a.5.5 0 0 0 .5.5H6v-1.5a.5.5 0 0 0-.5-.5H5v-.5a.5.5 0 0 0-.5-.5H3z"/>
                    </svg>
                </a>
            </div>
            <p>{{ post.pub_date.strftime('%Y-%m-%d') }}</p>
            <p>{{ post.body }}</p>
        </div>
    {% endif %}
{% endfor %}

{% endblock %}

blog/templates/login_form.html
<!-- blog/templates/login_form.html -->
{% extends "base.html" %}

{% block content %}

<h3>
  Увійди
</h3>

{% if errors %}
   {{ errors.username }}
{% endif %}
<form action="" method="POST">
  {{form.hidden_tag()}}
   <div class="form-group">
       <label id="title">Ім'я користувача</label>
       {% if errors and errors.username %}
           {{ form.username(class_="form-control is-invalid") }}
       {% else %}
           {{ form.username(class_="form-control") }}
       {% endif %}
       <div class="invalid-feedback">{{ errors.username|join(' ') }}</div>

   </div>
   <div class="form-group">
       <label id="body">Пароль</label>

       {% if errors and errors.password %}
           {{ form.password(class_="form-control is-invalid") }}
       {% else %}
           {{ form.password(class_="form-control") }}
       {% endif %}
       <div class="invalid-feedback">{{ errors.password|join(' ') }}</div>

   </div>
   <button type="submit" class="btn btn-primary mt-5">Увійди</button>
</form>

{% endblock %}